name: cola
description: A Very Good Project created by Very Good CLI.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.1
  cli_completion: ^0.3.0
  image: ^4.0.15
  mason_logger: ^0.2.4
  process_run: ^0.12.5+3
  pub_updater: ^0.2.4


dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0+1

executables:
  cola:
